In [1]:
import numpy as np

In [2]:
learning_rate = 1.0

In [3]:
x = np.array([[1.0, 2.0, 1.0], # 1st data point: x1, x2 + bias
             [2.0, 1.0, 1.0]]) # 2nd data point

In [4]:
ytrue = np.array([1.0, 0.0])

In [5]:
wh = np.array([[3.0, 4.0, -1.0],  # weights of 1st hidden neuron
               [-2.0, 0.5, 9.0]])

In [6]:
wo = np.array([[3.0, 2.0, 1.0]])

In [7]:
ypred = np.array([0.9, 0.7])

In [8]:
hidden_out = np.array([[0.5, 0.2, 1.0], [0.1, 0.8, 1.0]])

In [9]:
# equation 1: CALCULATING THE ERROR

error = ypred - ytrue

In [10]:
error

# that means prediction for data point 1 ist to low and second point to big

array([-0.1,  0.7])

In [11]:
# equation 2: CALCULATING THE OUTPUT GRADIENT

delta_y = ypred * (1 - ypred) * error

In [12]:
delta_y

# here you can see that the second point is the most relevant and the first not to much

array([-0.009,  0.147])

In [13]:
grad_y = ypred * (1 - ypred) * error

In [14]:
# Equation 3: CALCULATE WEIGHT MODIFICATION FOR OUTPUT LAYER

delta_output_weight = np.dot(-grad_y, hidden_out) * learning_rate
delta_output_weight

array([-0.0102, -0.1158, -0.138 ])

In [15]:
wo += delta_output_weight
wo

array([[2.9898, 1.8842, 0.862 ]])

In [29]:
# EQUATION 4+5: BACKPROPAGATION TO THE HIDDEN LAYER

grad_h = hidden_out * (1 - hidden_out) * np.dot(grad_y, wo)

ValueError: shapes (2,) and (1,3) not aligned: 2 (dim 0) != 1 (dim 0)

In [30]:
grad_h = hidden_out * (1 - hidden_out) * np.dot(wo[:,:2], grad_y)

In [31]:
delta_hiddden_weight = np.dot(-grad_h.T, x) * learning_rate

In [32]:
delta_hiddden_weight

array([[-0.10752976, -0.14754083, -0.08502353],
       [-0.12003322, -0.12003322, -0.08002214],
       [ 0.        ,  0.        ,  0.        ]])

In [33]:
wh += delta_hiddden_weight
wh

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) (2,3) 

In [23]:
grad_h = hidden_out * (1 - hidden_out) * np.dot(wo[:,:2], grad_y)

In [24]:
grad_h

array([[0.0625173 , 0.04001107, 0.        ],
       [0.02250623, 0.04001107, 0.        ]])

In [26]:
delta_hidden_weight = np.dot(-grad_h, x) * learning_rate

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [27]:
# Transpose to have an idea of a result

delta_hidden_weight = np.dot(-grad_h.T, x) * learning_rate

In [28]:
delta_hidden_weight

array([[-0.10752976, -0.14754083, -0.08502353],
       [-0.12003322, -0.12003322, -0.08002214],
       [ 0.        ,  0.        ,  0.        ]])