In [1]:
import numpy as np

In [3]:
X = np.array([
    [0, 0, 1],
    [1, 0, 1],
    [0, 1, 1],
    [1, 1, 1]])

In [4]:
weights_AND = np.array([1.0, 1.0, 0.0])

weights_OR = np.array([1.0, 1.0, 1.0])

In [6]:
np.dot(X, weights_AND)

array([0., 1., 1., 2.])

In [7]:
def step(x):
    return x > 1.0

In [8]:
step(np.dot(X, weights_AND))

array([False, False, False,  True])

In [9]:
step(np.dot(X, weights_OR))

array([False,  True,  True,  True])