In [1]:
import pandas as pd
import numpy as np

path = 'C:/Users/Pippo/Desktop/python_examples/Week_05/'

df = pd.read_csv('Items_csv.pl', index_col=0)
df


height  width  depth
item                               
blue cylinder    14.9    4.5    4.5
green cube        5.0    5.0    4.5
wooden ball       7.0    7.0    7.0
spiky ball        6.0    6.0    6.0
minion            4.0    2.0    2.0
red cylinder      4.0    4.0    4.0
penguin          10.0    3.0    3.0
disc             10.0   10.0    1.5

In [2]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler

In [3]:
df.var()

height    14.344107
width      6.281250
depth      3.531250
dtype: float64

In [4]:
scaler = MinMaxScaler()
scaler

MinMaxScaler(copy=True, feature_range=(0, 1))

In [5]:
X = df - df.mean()
X

height   width   depth
item                                 
blue cylinder  7.2875 -0.6875  0.4375
green cube    -2.6125 -0.1875  0.4375
wooden ball   -0.6125  1.8125  2.9375
spiky ball    -1.6125  0.8125  1.9375
minion        -3.6125 -3.1875 -2.0625
red cylinder  -3.6125 -1.1875 -0.0625
penguin        2.3875 -2.1875 -1.0625
disc           2.3875  4.8125 -2.5625

In [6]:
X.mean()

height    2.220446e-16
width     0.000000e+00
depth     0.000000e+00
dtype: float64

In [7]:
pca = PCA(n_components=3)
pca

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [8]:
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [9]:
Xt = pca.transform(X)

In [10]:
Xt

array([[ 6.88494086, -2.19455231, -1.24629384],
       [-2.59508667,  0.51605817, -0.22567204],
       [-0.26675242,  2.54187154, -2.3993647 ],
       [-1.44027364,  1.58768127, -1.55534523],
       [-4.19484   , -2.68118524,  1.63669846],
       [-3.78731608, -0.32069928,  0.13269371],
       [ 1.82747753, -2.85725851,  0.3325935 ],
       [ 3.57185042,  3.40808434,  3.32469013]])

In [11]:
pca.components_

array([[ 0.96975926,  0.24117833, -0.03741637],
       [-0.22605271,  0.94537733,  0.23486565],
       [-0.0920171 ,  0.21930507, -0.97130744]])

In [12]:
pca.explained_variance_ratio_

array([0.61693069, 0.24326256, 0.13980676])

In [13]:
df2 = pd.DataFrame(Xt, columns=['size', 'longness', 'discness'], index=df.index).round(2)

In [14]:
df2.sort_values(by='size')

size  longness  discness
item                                   
minion        -4.19     -2.68      1.64
red cylinder  -3.79     -0.32      0.13
green cube    -2.60      0.52     -0.23
spiky ball    -1.44      1.59     -1.56
wooden ball   -0.27      2.54     -2.40
penguin        1.83     -2.86      0.33
disc           3.57      3.41      3.32
blue cylinder  6.88     -2.19     -1.25

In [15]:
df2.sort_values(by='longness')

size  longness  discness
item                                   
penguin        1.83     -2.86      0.33
minion        -4.19     -2.68      1.64
blue cylinder  6.88     -2.19     -1.25
red cylinder  -3.79     -0.32      0.13
green cube    -2.60      0.52     -0.23
spiky ball    -1.44      1.59     -1.56
wooden ball   -0.27      2.54     -2.40
disc           3.57      3.41      3.32

In [16]:
df2.sort_values(by='discness')

size  longness  discness
item                                   
wooden ball   -0.27      2.54     -2.40
spiky ball    -1.44      1.59     -1.56
blue cylinder  6.88     -2.19     -1.25
green cube    -2.60      0.52     -0.23
red cylinder  -3.79     -0.32      0.13
penguin        1.83     -2.86      0.33
minion        -4.19     -2.68      1.64
disc           3.57      3.41      3.32

In [17]:
pca = PCA(n_components=2)

In [18]:
Xt = pca.fit_transform(X)

In [19]:
pca.explained_variance_ratio_

array([0.61693069, 0.24326256])

In [20]:
pca.components_

array([[ 0.96975926,  0.24117833, -0.03741637],
       [-0.22605271,  0.94537733,  0.23486565]])

In [21]:
np.dot(X.values, pca.components_.T)

array([[ 6.88494086, -2.19455231],
       [-2.59508667,  0.51605817],
       [-0.26675242,  2.54187154],
       [-1.44027364,  1.58768127],
       [-4.19484   , -2.68118524],
       [-3.78731608, -0.32069928],
       [ 1.82747753, -2.85725851],
       [ 3.57185042,  3.40808434]])