# Selecting and modifying arrays

In [1]:
import numpy as np

In [2]:
a = np.arange(12)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Exercise 2

Replace odd numbers by -1

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [5]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a[1::2] = -1

In [8]:
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [9]:
a[a % 2 == 1] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# Exercise 3

Retrieve positions where elements of a and b match

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

In [10]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

In [11]:
a[a==b]

array([2, 2, 4, 4])

In [12]:
a==b

array([False,  True, False,  True, False,  True, False,  True, False,
       False])

In [13]:
# hard solution 

[i for i, x in enumerate(a)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
[i for i, x in enumerate(a) if x==b[i]]

[1, 3, 5, 7]

In [17]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

i = 0 

result = []
for x in a:
    if x == b[i]:
        result.append(i)
        
result

[]

In [20]:
i = np.arange(10)
i

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
i[a==b]

array([1, 3, 5, 7])

In [22]:
np.arange(10)[a==b]

array([1, 3, 5, 7])

# Exercise 4

Drop all missing values from a numpy array

a = np.array([1,2,3,np.nan,5,6,7,np.nan])

In [26]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])

In [27]:
a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7.])

In [29]:
b = np.isnan(a)
b

array([False, False, False,  True, False, False, False,  True])

In [30]:
a[~b]

array([1., 2., 3., 5., 6., 7.])

In [32]:
a[b!=True]

array([1., 2., 3., 5., 6., 7.])