In [1]:
data = [-1.0, -.75, -.5, -.25, 0,0, .25, .50, .75, 1.0]


In [2]:
x1 = [-1.0, -.75, -.5, -.25, 0,0, .25, .50, .75, 1.0]

In [3]:
x2 = [abs(i) for i in x1]

x2

[1.0, 0.75, 0.5, 0.25, 0, 0, 0.25, 0.5, 0.75, 1.0]

In [4]:
y = [1, 1, 1, 0, 0, 0, 1, 1, 1]

In [5]:
from sklearn.linear_model import LogisticRegression

In [6]:
m = LogisticRegression()

In [7]:
import numpy as np

In [8]:
X = np.array([x1])
y = np.array(y)

In [9]:
import pandas as pd

In [10]:
x = pd.Series([1.0, np.NaN, 2.0, 3.0, np.NaN, np.NaN, 6.0, 1.0, 1.0])

x

0    1.0
1    NaN
2    2.0
3    3.0
4    NaN
5    NaN
6    6.0
7    1.0
8    1.0
dtype: float64

In [11]:
# how we can put a value in the NaN values? 

# we can use the mean() or median() depending the case

x.mean()

2.3333333333333335

In [12]:
# use the method "fillna" to fill the NaN

x.fillna(x.median())

0    1.0
1    1.5
2    2.0
3    3.0
4    1.5
5    1.5
6    6.0
7    1.0
8    1.0
dtype: float64

In [13]:
x

0    1.0
1    NaN
2    2.0
3    3.0
4    NaN
5    NaN
6    6.0
7    1.0
8    1.0
dtype: float64

In [14]:
# interpolation - takes the bounderies and fill the numbers as in the example below:

# interpolation is good for time problems (please check interpolation + shift to get more information and functions)

x.interpolate('linear')

0    1.0
1    1.5
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    1.0
8    1.0
dtype: float64

In [15]:
#?x.interpolate

x.interpolate('quadratic')

0    1.000000
1    1.372102
2    2.000000
3    3.000000
4    5.069941
5    7.574067
6    6.000000
7    1.000000
8    1.000000
dtype: float64

In [16]:
x.dropna()

0    1.0
2    2.0
3    3.0
6    6.0
7    1.0
8    1.0
dtype: float64

In [17]:

?x.fillna

x.fillna(0.0)

0    1.0
1    0.0
2    2.0
3    3.0
4    0.0
5    0.0
6    6.0
7    1.0
8    1.0
dtype: float64

In [18]:
x.interpolate('linear', inplace=True)

x

0    1.0
1    1.5
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    1.0
8    1.0
dtype: float64

In [19]:
# then we have to normalize our information

x.abs()

0    1.0
1    1.5
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    1.0
8    1.0
dtype: float64

In [20]:
x ** 2

0     1.00
1     2.25
2     4.00
3     9.00
4    16.00
5    25.00
6    36.00
7     1.00
8     1.00
dtype: float64

In [21]:
x ** 3

0      1.000
1      3.375
2      8.000
3     27.000
4     64.000
5    125.000
6    216.000
7      1.000
8      1.000
dtype: float64

In [22]:
np.log(x)

0    0.000000
1    0.405465
2    0.693147
3    1.098612
4    1.386294
5    1.609438
6    1.791759
7    0.000000
8    0.000000
dtype: float64

In [23]:
x / 99

0    0.010101
1    0.015152
2    0.020202
3    0.030303
4    0.040404
5    0.050505
6    0.060606
7    0.010101
8    0.010101
dtype: float64

In [24]:
x / 6.0

0    0.166667
1    0.250000
2    0.333333
3    0.500000
4    0.666667
5    0.833333
6    1.000000
7    0.166667
8    0.166667
dtype: float64

In [25]:
(x-min(x)) / (max(x) - min(x))

0    0.0
1    0.1
2    0.2
3    0.4
4    0.6
5    0.8
6    1.0
7    0.0
8    0.0
dtype: float64

In [26]:
from sklearn.preprocessing import MinMaxScaler 

In [27]:
# you can choose the scale you want to use put the numbers inside the ()

m = MinMaxScaler()

In [28]:
x.values.reshape(-1, 1)

array([[1. ],
       [1.5],
       [2. ],
       [3. ],
       [4. ],
       [5. ],
       [6. ],
       [1. ],
       [1. ]])

In [29]:
X = x.values.reshape(-1, 1)

In [30]:
m.fit(X)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [31]:
m.transform(X)

array([[0. ],
       [0.1],
       [0.2],
       [0.4],
       [0.6],
       [0.8],
       [1. ],
       [0. ],
       [0. ]])

In [32]:

from sklearn.preprocessing import StandardScaler

In [33]:
m = StandardScaler()

In [34]:
m.fit(X)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [35]:
m.transform(X)

array([[-0.96686344],
       [-0.68616115],
       [-0.40545886],
       [ 0.15594572],
       [ 0.71735029],
       [ 1.27875487],
       [ 1.84015944],
       [-0.96686344],
       [-0.96686344]])

In [36]:
#save the resultl

g = m.transform(X)

In [37]:
np.mean(g)

-4.9343245538895844e-17

In [38]:
np.std(g)

0.9999999999999999

In [39]:
g

array([[-0.96686344],
       [-0.68616115],
       [-0.40545886],
       [ 0.15594572],
       [ 0.71735029],
       [ 1.27875487],
       [ 1.84015944],
       [-0.96686344],
       [-0.96686344]])

In [40]:

# BINNING 

# we need to pandas function "cut" - doing this the series will contain just 3 different values

pd.cut(x, bins=3)

0    (0.995, 2.667]
1    (0.995, 2.667]
2    (0.995, 2.667]
3    (2.667, 4.333]
4    (2.667, 4.333]
5      (4.333, 6.0]
6      (4.333, 6.0]
7    (0.995, 2.667]
8    (0.995, 2.667]
dtype: category
Categories (3, interval[float64]): [(0.995, 2.667] < (2.667, 4.333] < (4.333, 6.0]]

In [41]:

# we can give labels to the data so it is more readable.

pd.cut(x, bins=3, labels=[1, 2, 3])

0    1
1    1
2    1
3    2
4    2
5    3
6    3
7    1
8    1
dtype: category
Categories (3, int64): [1 < 2 < 3]

In [42]:

# another bin function is the "qcut" 

pd.qcut(x, q=3)

0    (0.999, 1.333]
1    (1.333, 3.333]
2    (1.333, 3.333]
3    (1.333, 3.333]
4      (3.333, 6.0]
5      (3.333, 6.0]
6      (3.333, 6.0]
7    (0.999, 1.333]
8    (0.999, 1.333]
dtype: category
Categories (3, interval[float64]): [(0.999, 1.333] < (1.333, 3.333] < (3.333, 6.0]]

In [43]:

pd.qcut(x, q=3, labels=[1, 2, 3])

0    1
1    2
2    2
3    2
4    3
5    3
6    3
7    1
8    1
dtype: category
Categories (3, int64): [1 < 2 < 3]

In [44]:

# save information

o = pd.qcut(x, q=3, labels=[1, 2, 3])

o

0    1
1    2
2    2
3    2
4    3
5    3
6    3
7    1
8    1
dtype: category
Categories (3, int64): [1 < 2 < 3]

In [45]:
# get dummies convert categories into biniry numbers!

pd.get_dummies(o)

1  2  3
0  1  0  0
1  0  1  0
2  0  1  0
3  0  1  0
4  0  0  1
5  0  0  1
6  0  0  1
7  1  0  0
8  1  0  0

In [46]:
s = pd.Series(['A', 'B', 'A', 'C', 'D'])

In [47]:
pd.get_dummies(s)

A  B  C  D
0  1  0  0  0
1  0  1  0  0
2  1  0  0  0
3  0  0  1  0
4  0  0  0  1

In [48]:
# to create a one column 

from sklearn.preprocessing import LabelEncoder


In [49]:
m = LabelEncoder()

In [50]:
m.fit(s)

LabelEncoder()

In [51]:
m.transform(s)

array([0, 1, 0, 2, 3])